FIND_PATH(LEPTONICA_INCLUDE_DIRS
        allheaders.h
        /usr/include/leptonica
        )
MESSAGE(STATUS "LEPTONICA_INCLUDE_DIRS: ${LEPTONICA_INCLUDE_DIRS}")

FIND_LIBRARY(LEPTONICA_LIBRARY
        NAMES lept
        PATHS
        /usr/lib
        /usr/lib64
        )
MESSAGE(STATUS "LEPTONICA_LIBRARY ${LEPTONICA_LIBRARY}")

# handle the QUIETLY and REQUIRED arguments and set LEPTONICA_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LEPTONICA DEFAULT_MSG LEPTONICA_LIBRARY LEPTONICA_INCLUDE_DIRS)

IF (LEPTONICA_FOUND)
    MESSAGE(STATUS "LEPTONICA found")
    SET(LEPTONICA_LIBRARIES ${LEPTONICA_LIBRARY})
ENDIF (LEPTONICA_FOUND)

MARK_AS_ADVANCED(LEPTONICA_INCLUDE_DIRS LEPTONICA_LIBRARY)